name: CDP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  build-extension:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        RepositoryUrl: 'https://github.com/${{ github.repository }}'
        RepositoryBranch: '${{ github.ref }}'
        SourceRevisionId: '${{ github.sha }}'
        VersionSuffix: 'pr-${{github.event.number}}.${{ github.run_number }}'
        Configuration: Release
        SolutionPath: src\RustAnalyzer.sln
        VsixManifestPath: src\RustAnalyzer\source.extension.vsixmanifest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore $env:SolutionPath
    - name: Calculate next version
      uses: cezarypiatek/NextVersionGeneratorAction@0.4
      with:
        minor-pattern: '\bAdd\b'
        patch-pattern: '.*'
        output-to-env-variable: 'VersionPrefix'
    - name: Set version for Visual Studio Extension
      uses: cezarypiatek/VsixVersionAction@1.0
      with:
        version: '${{env.VersionPrefix}}+${{env.VersionSuffix}}'
        vsix-manifest-file: ${{ env.VsixManifestPath }}
    - name: Build
      run: msbuild $env:SolutionPath /t:Rebuild
      env:
        DeployExtension: False
    - name: Test
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: '*.UnitTests.dll'
        searchFolder: ./src/**/Release/
        runInParallel: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: RustAnalyzer
        path: src\RustAnalyzer\bin\Release\RustAnalyzer.vsix
